# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_word_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWordDialog(object):
    def setupUi(self, AddWordDialog):
        AddWordDialog.setObjectName("AddWordDialog")
        AddWordDialog.resize(833, 800)
        AddWordDialog.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddWordDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(AddWordDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 817, 742))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.name_lineedit.setClearButtonEnabled(True)
        self.name_lineedit.setObjectName("name_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_lineedit)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.etymology_lineedit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.etymology_lineedit.setClearButtonEnabled(True)
        self.etymology_lineedit.setObjectName("etymology_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.etymology_lineedit)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pronunciation_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.pronunciation_groupbox.setTitle("")
        self.pronunciation_groupbox.setObjectName("pronunciation_groupbox")
        self.pronunciation_layout = QtWidgets.QVBoxLayout(self.pronunciation_groupbox)
        self.pronunciation_layout.setObjectName("pronunciation_layout")
        self.add_pronunciation_button = QtWidgets.QPushButton(self.pronunciation_groupbox)
        self.add_pronunciation_button.setObjectName("add_pronunciation_button")
        self.pronunciation_layout.addWidget(self.add_pronunciation_button, 0, QtCore.Qt.AlignRight)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pronunciation_groupbox)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.meanings_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.meanings_groupbox.setTitle("")
        self.meanings_groupbox.setObjectName("meanings_groupbox")
        self.meanings_layout = QtWidgets.QVBoxLayout(self.meanings_groupbox)
        self.meanings_layout.setContentsMargins(0, 0, 0, -1)
        self.meanings_layout.setObjectName("meanings_layout")
        self.add_meaning_button = QtWidgets.QPushButton(self.meanings_groupbox)
        self.add_meaning_button.setObjectName("add_meaning_button")
        self.meanings_layout.addWidget(self.add_meaning_button, 0, QtCore.Qt.AlignRight)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.meanings_groupbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddWordDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(AddWordDialog)
        self.buttonBox.accepted.connect(AddWordDialog.accept)
        self.buttonBox.rejected.connect(AddWordDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddWordDialog)

    def retranslateUi(self, AddWordDialog):
        _translate = QtCore.QCoreApplication.translate
        AddWordDialog.setWindowTitle(_translate("AddWordDialog", "Add Word - English Dictionary"))
        self.label.setText(_translate("AddWordDialog", "Name"))
        self.name_lineedit.setPlaceholderText(_translate("AddWordDialog", "king"))
        self.label_2.setText(_translate("AddWordDialog", "Etymology"))
        self.etymology_lineedit.setPlaceholderText(_translate("AddWordDialog", "Old English cyning, cyng, of Germanic origin; related to Dutch koning and German König, also to kin."))
        self.label_3.setText(_translate("AddWordDialog", "Pronunciations"))
        self.add_pronunciation_button.setToolTip(_translate("AddWordDialog", "Add another pronunciation form"))
        self.add_pronunciation_button.setText(_translate("AddWordDialog", "Add Pronunciation"))
        self.label_4.setText(_translate("AddWordDialog", "Meanings"))
        self.add_meaning_button.setToolTip(_translate("AddWordDialog", "Add another meanings form"))
        self.add_meaning_button.setText(_translate("AddWordDialog", "Add Meaning"))
