# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meanings_groupbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeaningsGroupBox(object):
    def setupUi(self, MeaningsGroupBox):
        MeaningsGroupBox.setObjectName("MeaningsGroupBox")
        MeaningsGroupBox.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MeaningsGroupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(MeaningsGroupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.part_of_speech_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.part_of_speech_lineedit.setClearButtonEnabled(True)
        self.part_of_speech_lineedit.setObjectName("part_of_speech_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.part_of_speech_lineedit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.definition_layout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.definition_layout.setContentsMargins(0, 0, 0, -1)
        self.definition_layout.setObjectName("definition_layout")
        self.add_definition_button = QtWidgets.QPushButton(self.groupBox_2)
        self.add_definition_button.setObjectName("add_definition_button")
        self.definition_layout.addWidget(self.add_definition_button, 0, QtCore.Qt.AlignRight)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupBox_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(MeaningsGroupBox)
        QtCore.QMetaObject.connectSlotsByName(MeaningsGroupBox)

    def retranslateUi(self, MeaningsGroupBox):
        _translate = QtCore.QCoreApplication.translate
        MeaningsGroupBox.setWindowTitle(_translate("MeaningsGroupBox", "Form"))
        self.label.setText(_translate("MeaningsGroupBox", "Part of Speech"))
        self.part_of_speech_lineedit.setPlaceholderText(_translate("MeaningsGroupBox", "noun"))
        self.label_2.setText(_translate("MeaningsGroupBox", "Definitions"))
        self.add_definition_button.setToolTip(_translate("MeaningsGroupBox", "Add another  definition form"))
        self.add_definition_button.setText(_translate("MeaningsGroupBox", "Add Definition"))
