# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pronunciation_groupbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pronunciation(object):
    def setupUi(self, Pronunciation):
        Pronunciation.setObjectName("Pronunciation")
        Pronunciation.resize(679, 326)
        self.verticalLayout = QtWidgets.QVBoxLayout(Pronunciation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Pronunciation)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pronunciation_text_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.pronunciation_text_lineedit.setClearButtonEnabled(True)
        self.pronunciation_text_lineedit.setObjectName("pronunciation_text_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pronunciation_text_lineedit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pronunciation_audio_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.pronunciation_audio_lineedit.setClearButtonEnabled(True)
        self.pronunciation_audio_lineedit.setObjectName("pronunciation_audio_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pronunciation_audio_lineedit)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Pronunciation)
        QtCore.QMetaObject.connectSlotsByName(Pronunciation)

    def retranslateUi(self, Pronunciation):
        _translate = QtCore.QCoreApplication.translate
        Pronunciation.setWindowTitle(_translate("Pronunciation", "Pronunciation"))
        self.label.setText(_translate("Pronunciation", "Text"))
        self.pronunciation_text_lineedit.setPlaceholderText(_translate("Pronunciation", "kɪŋ"))
        self.label_2.setText(_translate("Pronunciation", "Audio"))
        self.pronunciation_audio_lineedit.setPlaceholderText(_translate("Pronunciation", "//ssl.gstatic.com/dictionary/static/sounds/20200429/king--1_gb_1.mp3"))
