# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'related_words_groupbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RelatedWordsGroupBox(object):
    def setupUi(self, RelatedWordsGroupBox):
        RelatedWordsGroupBox.setObjectName("RelatedWordsGroupBox")
        RelatedWordsGroupBox.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(RelatedWordsGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(RelatedWordsGroupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.related_words_layout = QtWidgets.QFormLayout(self.groupBox)
        self.related_words_layout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.related_words_layout.setContentsMargins(0, 0, 0, 0)
        self.related_words_layout.setSpacing(6)
        self.related_words_layout.setObjectName("related_words_layout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.related_words_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.relationship_type_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.relationship_type_lineedit.setClearButtonEnabled(True)
        self.relationship_type_lineedit.setObjectName("relationship_type_lineedit")
        self.related_words_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.relationship_type_lineedit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.related_words_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.related_words_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.related_words_lineedit.setClearButtonEnabled(True)
        self.related_words_lineedit.setObjectName("related_words_lineedit")
        self.related_words_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.related_words_lineedit)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(RelatedWordsGroupBox)
        QtCore.QMetaObject.connectSlotsByName(RelatedWordsGroupBox)

    def retranslateUi(self, RelatedWordsGroupBox):
        _translate = QtCore.QCoreApplication.translate
        RelatedWordsGroupBox.setWindowTitle(_translate("RelatedWordsGroupBox", "Form"))
        self.label.setText(_translate("RelatedWordsGroupBox", "Relationship Type"))
        self.relationship_type_lineedit.setPlaceholderText(_translate("RelatedWordsGroupBox", "synonyms"))
        self.label_2.setText(_translate("RelatedWordsGroupBox", "Related Words"))
        self.related_words_lineedit.setPlaceholderText(_translate("RelatedWordsGroupBox", "ruler, sovereign, monarch"))
